name: Gesco Barcode Tool docker build and push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  get-app-version:
    name: 🔢 Get application version
    uses: ./.github/workflows/get-app-version.yaml

  docker:
    runs-on: [ self-hosted, Linux ]
    needs: [ get-app-version ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker registry ⚓
        uses: docker/login-action@v3
        with:
          registry: gesco-docker-releases.gesco-world.fr
          username: ${{ secrets.NEXUS_USER_WRITER }}
          password: ${{ secrets.NEXUS_PASSWORD_WRITER }}
      - name: Build and push ⚓🚢
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            gesco-docker-releases.gesco-world.fr/gesco/gesco-barcode-tool:latest
            gesco-docker-releases.gesco-world.fr/gesco/gesco-barcode-tool:${{needs.get-app-version.outputs.version_name}}
      - name: Inspect
        run: |
          docker buildx imagetools inspect gesco-docker-releases.gesco-world.fr/gesco/gesco-barcode-tool:latest
