name: Gesco Barcode Tool linux build and push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  get-flutter-version:
    name: 🦋 Get flutter version
    uses: ./.github/workflows/get-flutter-version.yaml

  get-app-version:
    name: 🔢 Get application version
    uses: ./.github/workflows/get-app-version.yaml

  build-linux:
    name: "Build Linux"
#    runs-on: [ self-hosted, Linux ]
    runs-on: ubuntu-latest
    needs: [ get-flutter-version, get-app-version ]
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.6.1
        with:
          channel: ${{ needs.get-flutter-version.outputs.flutter_version }}

      - name: Install Linux build tools
        run: sudo apt-get update && sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev squashfs-tools

      - name: Enable desktop
        run: flutter config --enable-linux-desktop

      - name: Get packages
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Flutter build app
        run: flutter build linux

      - name: Compress artifacts
        uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: linux-dev.zip

      - name: Upload Build Zip
        uses: actions/upload-artifact@v2.3.1
        with:
          name: gesco-barcode-tool-linux-dev.zip
          path: linux-dev.zip

      - name: Install appbuilder deps
        run: |
          sudo add-apt-repository universe
          sudo apt install libfuse2 libgtk-3-0

      - name: Install appimagebuilder
        run: |
          wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage
          chmod +x appimage-builder-x86_64.AppImage
          sudo mv appimage-builder-x86_64.AppImage /usr/local/bin/appimage-builder

      - name: Build AppImage
        run: |
          appimage-builder --recipe AppImageBuilder.yml

      - name: Upload Build AppImage
        uses: actions/upload-artifact@v2.3.1
        with:
          name: gesco-barcode-tool-linux-dev.AppImage
          path: Gesco-barcode-tool-latest-x86_64.AppImage
